Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2020-09, with the labels that each got.

#181 ✨ manager: add option to watch a specific namespace for reconciliation
  main.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/S

#183 🏃 misspelling
  controllers/packetcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#185 🐛 clusterctl init fail because manager does not use a canonical image name
  config/release/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/cluster-lifecycle, size/XS

#186 bump v0.3.3
  Makefile
  VERSION
  config/release/kustomization.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, sig/cluster-lifecycle, size/L
