Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2020-12, with the labels that each got.

#208 :running: Update version for v0.3.6
  VERSION
  config/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#214 :running: Update version for v0.3.7
  VERSION
  config/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#212 :bug: Fix error handling on Machine creation
  controllers/packetmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#210 :running: e2e config fixes
  test/e2e/config/packet-ci.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#211 :running: Update packngo to latest version
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#213 :sparkles: Fix typo in error message
  pkg/cloud/packet/client.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#216 ✨ use containerd as CRI
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#221 :sparkles: templates/cluster-template.yaml: consistently don't use sudo
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/S

#222 🏃 Update CAPI to v0.3.12
  go.mod
  go.sum
  test/e2e/config/packet-ci.yaml
  test/e2e/config/packet-dev.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/cluster-lifecycle, size/M
