Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2020-11, with the labels that each got.

#198 🐛 control plane template should use correct variable
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#200 :running: Bump version to v0.3.5
  VERSION
  config/release/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#202 *sparkles* Cluster Resource Set
  templates/cluster-template-crs.yaml
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XXL

#201 :running: e2e fixes
  Makefile
  config/kustomization.yaml
  config/manager/manager_image_patch.yaml
  test/e2e/config/packet-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/S

#204 ✨ Add e2e tests
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/ensure-kustomize.sh
  hack/ensure-packet-cli.sh
  hack/log/redact.sh
  scripts/ci-e2e.sh
  templates/addons/calico.yaml
  templates/cluster-template-ci.yaml
  test/e2e/Makefile
  test/e2e/common.go
  test/e2e/config/packet-ci.yaml
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/packet_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XXL

#206 :bug: Do not treat lack of reservations as a fatal error
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  controllers/packetmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#207 🏃 update capi to use release v0.3.11
  go.mod
  go.sum
  test/e2e/config/packet-ci.yaml
  test/e2e/config/packet-dev.yaml
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M
