Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2020-08, with the labels that each got.

#165 Update module path to sigs.k8s.io/cluster-api-provider-packet
  PROJECT
  README.md
  controllers/packetcluster_controller.go
  controllers/packetmachine_controller.go
  controllers/suite_test.go
  docs/concepts/machine.md
  go.mod
  go.sum
  hack/tools/go.mod
  main.go
  pkg/cloud/packet/client.go
  pkg/cloud/packet/scope/cluster.go
  pkg/cloud/packet/scope/machine.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#166 Enable Control Plane elastic ip management in CCM
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#167 Packetbot works night and day to keep Kubernetes under control
  README.md
  docs/banner.png
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#170 respect SERVICE_CIDR
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#175 ✨ manager: add health probes
  config/resources/manager/manager.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#178 ✨ manager: configure webhook port
  main.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#171 Add Dan Finneran as maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#176 📖 github: add Issue/PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#179 dependencies: update some dependencies and cluster-api
  Makefile
  go.mod
  go.sum
  test/e2e/config/packet-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#180 ✨ manager: add leader election namespace option
  main.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#182 manager: add option to configure the sync time
  main.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS
