Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2021-04, with the labels that each got.

#234 :sparkles: Increase defaults limits/requests for deployment
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, sig/cluster-lifecycle, size/XS

#232 Update klog dependency to v2
  controllers/suite_test.go
  go.mod
  go.sum
  hack/tools/go.sum
  pkg/cloud/packet/scope/cluster.go
  pkg/cloud/packet/scope/machine.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#235 :running: Add dependabot config and update go version for testing to v1.15
  .github/dependabot.yml
  .github/workflows/ci.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/S

#236 :running: Update dependencies
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L
