Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2021-03, with the labels that each got.

#229 ✨ Allow overriding facility
  api/v1alpha3/packetmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
  config/rbac/role.yaml
  pkg/cloud/packet/client.go
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#230 :running: Update versions in preparation for new release
  VERSION
  config/kustomization.yaml
Labels: cncf-cla: yes

#231 🐛 enable metrics scraping via prometheus
  config/rbac/auth_proxy_service.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS
