Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2022-07, with the labels that each got.

#341 :sparkles: bump golangci-lint version to v1.46.2
  Makefile
Labels: cncf-cla: yes, size/XS

#349 Test cleanup does not appear to purge SSH keys
  .gitignore
  cmd/ci-clean/main.go
Labels: cncf-cla: yes, approved, do-not-merge/invalid-commit-message, size/M

#350 Update CI to fetch tags.
  .github/workflows/ci.yaml
Labels: cncf-cla: yes

#351 Update pr and release to fetch tags.
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
Labels: cncf-cla: yes

#352 Add git diff HEAD to verify-gen
  Makefile
Labels: cncf-cla: yes, approved, size/XS

#353 Update go mods with new k8s versions
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes

#354 Include IP assigmenets when reconciling VIP ips
  pkg/cloud/packet/client.go
Labels: cncf-cla: yes, approved, size/XS

#359 Revert "Add User-Agent to Equinix Metal API calls"
  Makefile
  api/v1alpha3/zz_generated.conversion.go
  cmd/ci-clean/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
  go.mod
  go.sum
  hack/boilerplate/boilerplate.py
  pkg/cloud/packet/client.go
  scripts/go_install.sh
  templates/addons/calico.yaml
  test/e2e/capi_e2e_clusterctl_upgrade_test.go
  test/e2e/capi_e2e_conformance_test.go
  test/e2e/capi_e2e_quickstart_test.go
  test/e2e/capi_e2e_self_hosted_test.go
  test/e2e/capi_e2e_test.go
  test/e2e/capi_e2e_workload_upgrade_test.go
  test/e2e/common_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/suite_test.go
  version/version.go
Labels: cncf-cla: yes, approved, size/XXL

#363 :bug: Fix CPEM issues
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes, size/XS

#364 Revert ":bug: Fix CPEM issues"
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes

#365 :bug: Update Cloud Provider Equinix Metal Version
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/XS

#366 Bump k8s api versions and regenerate indirects
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L

#371 :sparkles: Use da11 as that's where machines are.
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, size/S, approved

#372 :sparkles: Add User-Agent support for Equinix Metal Calls
  cmd/ci-clean/main.go
  pkg/cloud/packet/client.go
  test/e2e/common_test.go
  test/e2e/suite_test.go
  version/version.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#376 :sparkles: bump cluster-api to 1.1.3
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
Labels: cncf-cla: yes, approved, size/M

#377 🐛 Update packngo calls
  Makefile
  pkg/cloud/packet/client.go
  test/e2e/common_test.go
  test/e2e/suite_test.go
  version/version.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#384 :sparkles: Remove-capp-e2e-tags
  Makefile
  cmd/ci-clean/main.go
  pkg/cloud/packet/client.go
Labels: cncf-cla: yes, size/S, approved

#387 :bug: Add release series to metadata.yaml file
  metadata.yaml
Labels: cncf-cla: yes, approved, size/XS
