Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2022-09, with the labels that each got.

#399 📖 Add example documentation for using kube-vip version of CAPP
  README.md
Labels: cncf-cla: yes, lgtm, size/S, approved

#405 ✨ Set up default environment for kubectl, crictl, etc.
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template-kube-vip-crs-cni.yaml
  templates/cluster-template-kube-vip.yaml
  templates/cluster-template.yaml
  templates/experimental-kube-vip/kustomization.yaml
  test/e2e/config/packet-ci-actions.yaml
Labels: cncf-cla: yes, approved, do-not-merge/invalid-commit-message, size/L

#406 :sparkles: Update to use 1.1.5 cluster-api libraries
  Makefile
  api/v1alpha3/zz_generated.conversion.go
  go.mod
  go.sum
  main.go
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, size/XL, lgtm, approved

#402 Readme updates
  README.md
  docs/MIGRATION.md
  docs/experiences/cni.md
  docs/experiences/flavors.md
Labels: cncf-cla: yes, lgtm, approved, size/L

#407 :book: Update build guide
  docs/BUILD.md
Labels: cncf-cla: yes, approved, size/M

#408 :bug: Fix dependabot PRs so gomod updates pass tests
  .github/dependabot.yml
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/M

#409 📖 Document usage of hardware reservations
  README.md
  docs/concepts/machine.md
  docs/contribution/e2e_test.md
Labels: cncf-cla: yes, lgtm, approved, size/L

#413 :running: Update-metadata-for-060-release
  README.md
  clusterctl-settings.json
  metadata.yaml
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M

#412 Update go install script and add kustomize install script
  Makefile
  scripts/go_install.sh
Labels: cncf-cla: yes, lgtm, size/S, approved

#436 Update templates
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template-kube-vip-crs-cni.yaml
  templates/cluster-template-kube-vip.yaml
  templates/cluster-template.yaml
  templates/experimental-kube-vip/kustomization.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M
