Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2023-10, with the labels that each got.

#615 Updated component-base/logs instead of old logging style
  main.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#660 :bug: Fix templates to use new k8s apt repository
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template-kube-vip-crs-cni.yaml
  templates/cluster-template-kube-vip.yaml
  templates/cluster-template.yaml
  templates/experimental-kube-vip/kustomization.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L

#661 :sparkles: Update to 1.4 CAPI
  .golangci.yml
  Makefile
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/packetcluster_types.go
  api/v1alpha3/packetmachine_types.go
  api/v1alpha3/packetmachinetemplate_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/packetcluster_types.go
  api/v1beta1/packetcluster_webhook.go
  api/v1beta1/packetmachine_types.go
  api/v1beta1/packetmachinetemplate_types.go
  api/v1beta1/packetmachinetemplate_webhook.go
  api/v1beta1/tags.go
  api/v1beta1/types.go
  cmd/ci-clean/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/packetcluster_controller.go
  controllers/packetmachine_controller.go
  go.mod
  go.sum
  main.go
  pkg/cloud/packet/client.go
  pkg/cloud/packet/scope/cluster.go
  pkg/cloud/packet/scope/machine.go
  pkg/cloud/packet/scope/machine_test.go
  pkg/cloud/packet/util.go
  test/e2e/capi_e2e_test.go
  test/e2e/common_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  version/version.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#664 :seedling: bump metal-go to v0.25.0
  api/v1alpha3/packetmachine_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1beta1/packetmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
  go.mod
  go.sum
  pkg/cloud/packet/client.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/M

#665 :bug: Bump to go 1.20.10 for rapid reset
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/M

#667 :seedling: bump dockerfile to use Go 1.20
  Dockerfile
  hack/boilerplate/boilerplate.Dockerfile.txt
Labels: cncf-cla: yes, approved, size/XS
