Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2023-04, with the labels that each got.

#552 Update packet-ci-actions.yaml
  test/e2e/config/packet-ci-actions.yaml
Labels: cncf-cla: yes, approved, size/XS

#553 Update packet-ci.yaml
  test/e2e/config/packet-ci.yaml
Labels: cncf-cla: yes, approved, size/XS

#554 Update clusterctl-settings.json
  clusterctl-settings.json
Labels: cncf-cla: yes, approved, size/XS

#555 :bug: Update metadata.yaml to include definitions for 1.3 and 1.4 capi
  test/e2e/config/packet-ci.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: cncf-cla: yes, size/S, approved

#559 Update e2e intervals
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
Labels: cncf-cla: yes, approved, size/M

#561 :bug: Update-e2e-harness
  .github/workflows/ci.yaml
  Makefile
  scripts/go_install.sh
  test/e2e/capi_e2e_clusterctl_upgrade_test.go
  test/e2e/capi_e2e_self_hosted_test.go
  test/e2e/capi_e2e_workload_upgrade_test.go
Labels: cncf-cla: yes, approved, size/M

#562 Remove single quote from test names
  Makefile
Labels: cncf-cla: yes

#563 :sparkles: Update github actions
  .github/actions/metadata/action.yaml
  .github/actions/setup-go/action.yaml
Labels: cncf-cla: yes, size/S, approved

#568 :bug: Github-actions
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/setup-go/action.yaml
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
Labels: cncf-cla: yes, approved, size/L

#569 :sparkle: add github token to ci workflows
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, approved, size/XS

#538 🏃 :sparkles: Add-metro-support
  .github/workflows/ci.yaml
  README.md
  api/v1alpha3/packetcluster_types.go
  api/v1alpha3/packetmachine_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1beta1/packetcluster_types.go
  api/v1beta1/packetcluster_webhook.go
  api/v1beta1/packetmachine_types.go
  api/v1beta1/packetmachine_webhook.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
  controllers/packetcluster_controller.go
  controllers/packetmachine_controller.go
  pkg/cloud/packet/client.go
  scripts/ci-e2e-capi-conformance.sh
  scripts/ci-e2e-capi-management-upgrade.sh
  scripts/ci-e2e-capi-quickstart.sh
  scripts/ci-e2e-capi-workload-upgrade.sh
  scripts/ci-e2e-capi.sh
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template-kube-vip-crs-cni.yaml
  templates/cluster-template-kube-vip.yaml
  templates/cluster-template.yaml
  test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml
  test/e2e/data/v1alpha3/bases/cluster-with-kcp-packet-ccm.yaml
Labels: cncf-cla: yes, approved, size/L

#574 :bug: Remove facility from kube-vip templates
  templates/cluster-template-kube-vip-crs-cni.yaml
  templates/cluster-template-kube-vip.yaml
  templates/experimental-kube-vip/kustomization.yaml
Labels: cncf-cla: yes, size/XS

#578 :sparkles: Refactor CI pipeline
  .github/actions/metadata/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  Makefile
  scripts/ci-e2e-capi-management-upgrade.sh
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
  test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml
  test/e2e/data/v1alpha3/bases/cluster-with-kcp-packet-ccm.yaml
Labels: cncf-cla: yes, approved, size/L

#576 :bug: Move to 20.04 as default
  README.md
  docs/concepts/machine.md
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template-kube-vip-crs-cni.yaml
  templates/cluster-template-kube-vip.yaml
  templates/cluster-template.yaml
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
  test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml
  test/e2e/data/v1alpha3/bases/cluster-with-kcp-packet-ccm.yaml
  test/e2e/data/v1alpha3/bases/md.yaml
Labels: cncf-cla: yes, approved, size/M

#577 :sparkles: Sync up kubeuilder tools version to upstream
  scripts/fetch_ext_bins.sh
Labels: cncf-cla: yes, approved, size/XS

#575 :bug: Kube vip updates
  templates/cluster-template-kube-vip-crs-cni.yaml
  templates/cluster-template-kube-vip.yaml
  templates/experimental-kube-vip/kustomization.yaml
Labels: cncf-cla: yes, size/S, approved

#580 :sparkles: Refactor release ci and go back to using quay as default
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
Labels: cncf-cla: yes, approved, size/L

#581 :bug: Fix the registry variable in the release and ci yamls
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: cncf-cla: yes, approved, size/XS

#583 ci: update registry again to a valid format
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, approved

#584 ✨ Use GITHUB_TOKEN to avoid rate limits
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
Labels: cncf-cla: yes, approved, size/XS

#585 ✨Modify type.go to include shortNames for few Packet CRDs
  api/v1alpha3/packetcluster_types.go
  api/v1alpha3/packetmachine_types.go
  api/v1alpha3/packetmachinetemplate_types.go
  api/v1beta1/packetcluster_types.go
  api/v1beta1/packetmachine_types.go
  api/v1beta1/packetmachinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#586 Push Release v0.7.0
  README.md
  docs/RELEASE.md
  metadata.yaml
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template-kube-vip-crs-cni.yaml
  templates/cluster-template-kube-vip.yaml
  templates/cluster-template.yaml
  templates/experimental-kube-vip/kustomization.yaml
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
  test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml
Labels: cncf-cla: yes, size/S, approved
