Repository kubernetes-sigs/cluster-api-provider-packet, pull requests merged in 2023-12, with the labels that each got.

#674 :sparkles: CAPI 1.5 support
  .github/workflows/ci.yaml
  .gitignore
  .golangci.yml
  Dockerfile
  Makefile
  api/v1alpha3/doc.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/packetcluster_conversion.go
  api/v1alpha3/packetcluster_types.go
  api/v1alpha3/packetmachine_conversion.go
  api/v1alpha3/packetmachine_types.go
  api/v1alpha3/packetmachinetemplate_conversion.go
  api/v1alpha3/packetmachinetemplate_types.go
  api/v1alpha3/tags.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1beta1/packetcluster_webhook.go
  api/v1beta1/packetmachine_webhook.go
  api/v1beta1/packetmachinetemplate_webhook.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
  config/crd/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/packetcluster_controller.go
  controllers/packetmachine_controller.go
  go.mod
  go.sum
  main.go
  pkg/cloud/packet/scope/machine.go
  pkg/cloud/packet/scope/machine_test.go
  pkg/cloud/packet/util.go
  test/e2e/capi_e2e_clusterctl_upgrade_test.go
  test/e2e/capi_e2e_conformance_test.go
  test/e2e/capi_e2e_quickstart_test.go
  test/e2e/capi_e2e_workload_upgrade_test.go
  test/e2e/common_test.go
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml
  test/e2e/data/v1alpha3/bases/cluster-with-kcp-packet-ccm.yaml
  test/e2e/data/v1alpha3/bases/crs-cni.yaml
  test/e2e/data/v1alpha3/bases/md.yaml
  test/e2e/data/v1alpha3/cluster-template-cpem/kustomization.yaml
  test/e2e/data/v1alpha3/cluster-template-packet-ccm/kustomization.yaml
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/suite_test.go
  tilt-provider.json
Labels: cncf-cla: yes, lgtm, release-note-action-required, approved, size/XXL

#691 :sparkles: Update to Cluster API 1.6
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
  api/v1beta1/groupversion_info.go
  api/v1beta1/packetcluster_types.go
  api/v1beta1/packetmachine_types.go
  api/v1beta1/packetmachinetemplate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/packetcluster_controller.go
  controllers/packetmachine_controller.go
  go.mod
  go.sum
  main.go
  pkg/cloud/packet/scope/cluster.go
  pkg/cloud/packet/scope/machine.go
  templates/addons/calico.yaml
  templates/addons/calico/kustomization.yaml
  templates/cluster-template-crs-cni.yaml
  templates/cluster-template-kube-vip-crs-cni.yaml
  templates/cluster-template-kube-vip.yaml
  templates/cluster-template.yaml
  templates/experimental-kube-vip/kustomization.yaml
  test/e2e/common_test.go
  test/e2e/config/packet-ci-actions.yaml
  test/e2e/config/packet-ci.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#690 chore: switch from metal-go to equinix-sdk-go
  api/v1beta1/packetmachine_types.go
  cmd/ci-clean/main.go
  controllers/packetmachine_controller.go
  go.mod
  go.sum
  pkg/cloud/packet/client.go
  test/e2e/common_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/suite_test.go
  version/version.go
Labels: cncf-cla: yes, lgtm, size/S, approved
